fix(templates): fix error handling and route method call
commercetools/connect-application-kit pull request #83
Opened 2024-07-16 13:27 UTC by ruidias-commercetools

## Link to the Jira issue
### This PR will englobe two tickets
[IM-1114] https://jira.commercetools.com/browse/IM-1114
and
[IM-1117] https://jira.commercetools.com/browse/IM-1117

## Description and context
Since the work was fairly straightforward, we used just one PR to fix both tickets. 

So, this PR will close #78 and close #80.

Assessing #78, a new implementation was introduced, as suggested, to call the next() function inside a `try-catch` block.
```
serviceRouter.post('/', async (req, res, next) => {
  logger.info('Service post message received');

  try {
    await post(req, res);
    res.status(200).send();
  } catch (error) {
    next(error);
  }
});
```
Regarding #80, the following files were updated to call the correct controller methods inside the routes.
```
- application-templates/javascript/event/src/routes/event.route.js
- application-templates/javascript/job/src/routes/job.route.js
- application-templates/javascript/service/src/routes/service.route.js

- application-templates/typescript/event/src/routes/event.route.ts
- application-templates/typescript/job/src/routes/job.route.ts
- application-templates/typescript/service/src/routes/service.route.ts
```

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

2024-07-18 17:28 UTC, abreu-ct requested changes

2024-07-18 17:28 UTC, abreu-ct commented on application-templates/javascript/event/src/routes/event.route.js
> +    await post(req.body);
We need to pass the request and response instead.

2024-07-18 17:28 UTC, abreu-ct commented on application-templates/javascript/event/src/routes/event.route.js
> +    res.status(200).send();
If we are "proxying" the request and response here (not know the real reason) to the `event.controller.js`, then it is their responsibility to define the HTTP status and response body.

2024-07-22 16:14 UTC, abreu-ct approved these changes

2024-07-22 18:46 UTC, harm-meijer approved these changes

2024-07-22 20:34 UTC, merged